title = "Hugo + Netlify"
DefaultContentLanguage = "en"
baseURL = "https://www.example.com"

#Disable Hugo's built-in Alias feature, to utilize Netlify Redirects instead:
disableAliases = true

#Custom Output formats are outlined here: https://gohugo.io/templates/output-formats. See also: https://gohugo.io/news/http2-server-push-in-hugo/

# Create the media type https://gohugo.io/templates/output-formats#media-types
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

# configure output formats: https://gohugo.io/templates/output-formats#configure-output-formats
[outputFormats]
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputFormats.REDIR]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

# For the home page, output the formats we created: https://gohugo.io/templates/output-formats#customizing-output-formats
[outputs]
home = [
"HTML",
"HEADERS",
"REDIR"
]

