# Build commands here override any commands set in the Netlify Control panel

[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.47.1"

[context.production.environment]
HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
HUGO_ENV = "development"
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
HUGO_ENV = "development"
command = "hugo --gc -b $DEPLOY_PRIME_URL"

# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
